#!/usr/bin/env php
<?php

// 加载 Composer 自动加载
require __DIR__ . '/vendor/autoload.php';

use Anon\Core\Console\Application;
use Anon\Core\Foundation\App;

// 定义命令行环境下的基础常量
define('BASE_PATH', __DIR__);
define('APP_PATH', BASE_PATH . DIRECTORY_SEPARATOR . 'app');
define('RUNTIME_PATH', BASE_PATH . DIRECTORY_SEPARATOR . 'runtime');

// 实例化控制台应用
$console = new Application(App::VERSION);

// 运行控制台应用并传递命令行参数 ($argv)
$status = $console->run($argv);

// 退出进程
exit($status);