<?php
if (!defined('ANON_ALLOWED_ACCESS')) exit;

return [
    '基础设置' => [
        'color_scheme' => [
            'type' => 'select',
            'label' => '默认主题',
            'default' => 'garden',
            'options' => [
                'light' => '浅色',
                'dark' => '深色',
                'cupcake' => '奶油',
                'bumblebee' => '蜜蜂',
                'emerald' => '翡翠',
                'corporate' => '商务',
                'synthwave' => '合成波',
                'retro' => '复古',
                'cyberpunk' => '赛博朋克',
                'valentine' => '情人节',
                'halloween' => '万圣节',
                'garden' => '花园',
                'forest' => '森林',
                'aqua' => '水色',
                'lofi' => '低保真',
                'pastel' => '粉彩',
                'fantasy' => '奇幻',
                'wireframe' => '线框',
                'black' => '黑色',
                'luxury' => '奢华',
                'dracula' => '德古拉',
                'cmyk' => 'CMYK',
                'autumn' => '秋天',
                'business' => '商业',
                'acid' => '酸性',
                'lemonade' => '柠檬水',
                'night' => '夜晚',
                'coffee' => '咖啡',
                'winter' => '冬天',
                'dim' => '昏暗',
                'nord' => '北欧',
                'sunset' => '日落',
            ],
        ],
        'post_count' => [
            'type' => 'number',
            'label' => '首页日志数',
            'default' => 15,
            'min' => 5,
            'max' => 50,
        ],
        'show_date_badge' => [
            'type' => 'checkbox',
            'label' => '显示日期徽章',
            'description' => '在日志卡片上显示日期',
            'default' => true,
        ],
        'navbar_links' => [
            'type' => 'text_list',
            'label' => '顶部导航',
            'description' => '网站顶部导航，格式为 title|url',
            'default' => [
                '首页|' . $this->siteUrl(),
            ],
            'listPlaceholder' => '关于|/about',
        ],
        'icp_number' => [
            'type' => 'text',
            'label' => 'ICP备案号',
            'description' => '例如：京ICP备12345678号',
            'default' => '',
            'placeholder' => '京ICP备12345678号',
        ],
        'police_number' => [
            'type' => 'text',
            'label' => '公安备案号',
            'description' => '例如：京公网安备 11000002000001号',
            'default' => '',
            'placeholder' => '京公网安备 11000002000001号',
        ],
    ],
    '评论设置' => [
        'enable_comments' => [
            'type' => 'checkbox',
            'label' => '启用评论',
            'description' => '是否开启文章评论功能',
            'default' => true,
        ],
        'require_login_comment' => [
            'type' => 'checkbox',
            'label' => '登录后可评论',
            'description' => '仅允许登录用户发表评论',
            'default' => false,
        ],
        'comments_per_page' => [
            'type' => 'number',
            'label' => '每页评论数',
            'default' => 20,
            'min' => 5,
            'max' => 100,
        ],
        'comment_order' => [
            'type' => 'select',
            'label' => '评论排序',
            'default' => 'desc',
            'options' => [
                'desc' => '最新评论在前',
                'asc' => '最早评论在前',
            ],
        ],
        'enable_comment_avatar' => [
            'type' => 'checkbox',
            'label' => '显示评论头像',
            'default' => true,
        ],
        'avatar_source' => [
            'type' => 'select',
            'label' => '头像来源',
            'default' => 'gravatar',
            'options' => [
                'gravatar' => 'Gravatar',
                'cravatar' => 'Cravatar（国内加速）',
                'qq' => 'QQ头像',
            ],
        ],
    ],
    '自定义代码' => [
        'custom_code_head' => [
            'type' => 'textarea',
            'label' => '头部代码',
            'description' => '在 <head> 标签内插入代码',
            'default' => '',
        ],
        'custom_code_foot' => [
            'type' => 'textarea',
            'label' => '底部代码',
            'description' => '在 </body> 标签前插入代码',
            'default' => '',
        ],
    ],
];
