/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./src/components/AppFooter.vue')['default']
    AppHeader: typeof import('./src/components/AppHeader.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StatisticsCard: typeof import('./src/components/StatisticsCard.vue')['default']
    UApp: typeof import('./node_modules/.pnpm/@nuxt+ui@4.3.0_@babel+parse_225b0a400c94c9d6502ac4b8255b0acb/node_modules/@nuxt/ui/dist/runtime/components/App.vue')['default']
    UAvatar: typeof import('./node_modules/.pnpm/@nuxt+ui@4.3.0_@babel+parse_225b0a400c94c9d6502ac4b8255b0acb/node_modules/@nuxt/ui/dist/runtime/components/Avatar.vue')['default']
    UBadge: typeof import('./node_modules/.pnpm/@nuxt+ui@4.3.0_@babel+parse_225b0a400c94c9d6502ac4b8255b0acb/node_modules/@nuxt/ui/dist/runtime/components/Badge.vue')['default']
    UBlogPost: typeof import('./node_modules/.pnpm/@nuxt+ui@4.3.0_@babel+parse_225b0a400c94c9d6502ac4b8255b0acb/node_modules/@nuxt/ui/dist/runtime/components/BlogPost.vue')['default']
    UBlogPosts: typeof import('./node_modules/.pnpm/@nuxt+ui@4.3.0_@babel+parse_225b0a400c94c9d6502ac4b8255b0acb/node_modules/@nuxt/ui/dist/runtime/components/BlogPosts.vue')['default']
    UButton: typeof import('./node_modules/.pnpm/@nuxt+ui@4.3.0_@babel+parse_225b0a400c94c9d6502ac4b8255b0acb/node_modules/@nuxt/ui/dist/runtime/components/Button.vue')['default']
    UCard: typeof import('./node_modules/.pnpm/@nuxt+ui@4.3.0_@babel+parse_225b0a400c94c9d6502ac4b8255b0acb/node_modules/@nuxt/ui/dist/runtime/components/Card.vue')['default']
    UCheckbox: typeof import('./node_modules/.pnpm/@nuxt+ui@4.3.0_@babel+parse_225b0a400c94c9d6502ac4b8255b0acb/node_modules/@nuxt/ui/dist/runtime/components/Checkbox.vue')['default']
    UColorModeButton: typeof import('./node_modules/.pnpm/@nuxt+ui@4.3.0_@babel+parse_225b0a400c94c9d6502ac4b8255b0acb/node_modules/@nuxt/ui/dist/runtime/components/color-mode/ColorModeButton.vue')['default']
    UDropdownMenu: typeof import('./node_modules/.pnpm/@nuxt+ui@4.3.0_@babel+parse_225b0a400c94c9d6502ac4b8255b0acb/node_modules/@nuxt/ui/dist/runtime/components/DropdownMenu.vue')['default']
    UFooter: typeof import('./node_modules/.pnpm/@nuxt+ui@4.3.0_@babel+parse_225b0a400c94c9d6502ac4b8255b0acb/node_modules/@nuxt/ui/dist/runtime/components/Footer.vue')['default']
    UHeader: typeof import('./node_modules/.pnpm/@nuxt+ui@4.3.0_@babel+parse_225b0a400c94c9d6502ac4b8255b0acb/node_modules/@nuxt/ui/dist/runtime/components/Header.vue')['default']
    UIcon: typeof import('./node_modules/.pnpm/@nuxt+ui@4.3.0_@babel+parse_225b0a400c94c9d6502ac4b8255b0acb/node_modules/@nuxt/ui/dist/runtime/vue/components/Icon.vue')['default']
    UInput: typeof import('./node_modules/.pnpm/@nuxt+ui@4.3.0_@babel+parse_225b0a400c94c9d6502ac4b8255b0acb/node_modules/@nuxt/ui/dist/runtime/components/Input.vue')['default']
    UMain: typeof import('./node_modules/.pnpm/@nuxt+ui@4.3.0_@babel+parse_225b0a400c94c9d6502ac4b8255b0acb/node_modules/@nuxt/ui/dist/runtime/components/Main.vue')['default']
    UNavigationMenu: typeof import('./node_modules/.pnpm/@nuxt+ui@4.3.0_@babel+parse_225b0a400c94c9d6502ac4b8255b0acb/node_modules/@nuxt/ui/dist/runtime/components/NavigationMenu.vue')['default']
    UPageHeader: typeof import('./node_modules/.pnpm/@nuxt+ui@4.3.0_@babel+parse_225b0a400c94c9d6502ac4b8255b0acb/node_modules/@nuxt/ui/dist/runtime/components/PageHeader.vue')['default']
    UPageHero: typeof import('./node_modules/.pnpm/@nuxt+ui@4.3.0_@babel+parse_225b0a400c94c9d6502ac4b8255b0acb/node_modules/@nuxt/ui/dist/runtime/components/PageHero.vue')['default']
    USeparator: typeof import('./node_modules/.pnpm/@nuxt+ui@4.3.0_@babel+parse_225b0a400c94c9d6502ac4b8255b0acb/node_modules/@nuxt/ui/dist/runtime/components/Separator.vue')['default']
    UserMenu: typeof import('./src/components/UserMenu.vue')['default']
  }
}
