/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppHeader: typeof import('./src/components/AppHeader.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UApp: typeof import('./node_modules/.pnpm/@nuxt+ui@4.3.0_@babel+parse_8085f1a5a26afc67e0b13baab8b4d0a0/node_modules/@nuxt/ui/dist/runtime/components/App.vue')['default']
    UAvatar: typeof import('./node_modules/.pnpm/@nuxt+ui@4.3.0_@babel+parse_8085f1a5a26afc67e0b13baab8b4d0a0/node_modules/@nuxt/ui/dist/runtime/components/Avatar.vue')['default']
    UButton: typeof import('./node_modules/.pnpm/@nuxt+ui@4.3.0_@babel+parse_8085f1a5a26afc67e0b13baab8b4d0a0/node_modules/@nuxt/ui/dist/runtime/components/Button.vue')['default']
    UCard: typeof import('./node_modules/.pnpm/@nuxt+ui@4.3.0_@babel+parse_8085f1a5a26afc67e0b13baab8b4d0a0/node_modules/@nuxt/ui/dist/runtime/components/Card.vue')['default']
    UCheckbox: typeof import('./node_modules/.pnpm/@nuxt+ui@4.3.0_@babel+parse_8085f1a5a26afc67e0b13baab8b4d0a0/node_modules/@nuxt/ui/dist/runtime/components/Checkbox.vue')['default']
    UColorModeButton: typeof import('./node_modules/.pnpm/@nuxt+ui@4.3.0_@babel+parse_8085f1a5a26afc67e0b13baab8b4d0a0/node_modules/@nuxt/ui/dist/runtime/components/color-mode/ColorModeButton.vue')['default']
    UDropdownMenu: typeof import('./node_modules/.pnpm/@nuxt+ui@4.3.0_@babel+parse_8085f1a5a26afc67e0b13baab8b4d0a0/node_modules/@nuxt/ui/dist/runtime/components/DropdownMenu.vue')['default']
    UHeader: typeof import('./node_modules/.pnpm/@nuxt+ui@4.3.0_@babel+parse_8085f1a5a26afc67e0b13baab8b4d0a0/node_modules/@nuxt/ui/dist/runtime/components/Header.vue')['default']
    UInput: typeof import('./node_modules/.pnpm/@nuxt+ui@4.3.0_@babel+parse_8085f1a5a26afc67e0b13baab8b4d0a0/node_modules/@nuxt/ui/dist/runtime/components/Input.vue')['default']
    UMain: typeof import('./node_modules/.pnpm/@nuxt+ui@4.3.0_@babel+parse_8085f1a5a26afc67e0b13baab8b4d0a0/node_modules/@nuxt/ui/dist/runtime/components/Main.vue')['default']
    UNavigationMenu: typeof import('./node_modules/.pnpm/@nuxt+ui@4.3.0_@babel+parse_8085f1a5a26afc67e0b13baab8b4d0a0/node_modules/@nuxt/ui/dist/runtime/components/NavigationMenu.vue')['default']
    UserMenu: typeof import('./src/components/UserMenu.vue')['default']
    UTooltip: typeof import('./node_modules/.pnpm/@nuxt+ui@4.3.0_@babel+parse_8085f1a5a26afc67e0b13baab8b4d0a0/node_modules/@nuxt/ui/dist/runtime/components/Tooltip.vue')['default']
  }
}
